### ISSUE TITLE
Players cant join server

### ISSUE THREAD

**Issue by ThirtyTwelveNor** [abc123me/BetterForgeChat#2]
added to server but now no1 can join

[17:27:45] [Server thread/INFO] [minecraft/PlayerList]: KingGamerV4[/IP] logged in with entity id 338 at (3634.1428481626963, -44.0, 768.6999999880791)
[17:27:45] [Server thread/ERROR] [ne.mi.ev.EventBus/EVENTBUS]: Exception caught during firing event: Cannot invoke "java.lang.CharSequence.toString()" because "replacement" is null
        Index: 1
        Listeners:
                0: NORMAL
                1: ASM: com.jeremiahbl.bfcmod.events.PlayerEventHandler@644e2886 onTabListNameFormatEvent(Lnet/minecraftforge/event/entity/player/PlayerEvent$TabListNameFormat;)V
java.lang.NullPointerException: Cannot invoke "java.lang.CharSequence.toString()" because "replacement" is null
        at java.base/java.lang.String.replace(String.java:2956)
        at TRANSFORMER/bfcmod@1.1/com.jeremiahbl.bfcmod.utils.BetterForgeChatUtilities.getRawPreferredPlayerName(BetterForgeChatUtilities.java:23)
        at TRANSFORMER/bfcmod@1.1/com.jeremiahbl.bfcmod.utils.BetterForgeChatUtilities.getFormattedPlayerName(BetterForgeChatUtilities.java:29)
        at TRANSFORMER/bfcmod@1.1/com.jeremiahbl.bfcmod.events.PlayerEventHandler.onTabListNameFormatEvent(PlayerEventHandler.java:31)
        at net.minecraftforge.eventbus.ASMEventHandler_879_PlayerEventHandler_onTabListNameFormatEvent_TabListNameFormat.invoke(.dynamic)
        at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
        at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
        at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
        at TRANSFORMER/forge@40.1.61/net.minecraftforge.event.ForgeEventFactory.getPlayerTabListDisplayName(ForgeEventFactory.java:256)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.level.ServerPlayer.m_8957_(ServerPlayer.java:1355)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.network.protocol.game.ClientboundPlayerInfoPacket.<init>(ClientboundPlayerInfoPacket.java:28)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.level.ServerPlayerGameMode.m_9273_(ServerPlayerGameMode.java:64)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.level.ServerPlayer.m_143427_(ServerPlayer.java:1537)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.players.PlayerList.m_11261_(PlayerList.java:155)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.network.ServerLoginPacketListenerImpl.m_143699_(ServerLoginPacketListenerImpl.java:138)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.network.ServerLoginPacketListenerImpl.m_10055_(ServerLoginPacketListenerImpl.java:125)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.network.ServerLoginPacketListenerImpl.m_10050_(ServerLoginPacketListenerImpl.java:69)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.network.Connection.m_129483_(Connection.java:241)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:142)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:916)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:326)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:842)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:685)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261)
        at java.base/java.lang.Thread.run(Thread.java:833)
[17:27:45] [Server thread/ERROR] [minecraft/ServerLoginPacketListenerImpl]: Couldn't place player in world
java.lang.NullPointerException: Cannot invoke "java.lang.CharSequence.toString()" because "replacement" is null
        at java.lang.String.replace(String.java:2956) ~[?:?] {re:mixin}
        at com.jeremiahbl.bfcmod.utils.BetterForgeChatUtilities.getRawPreferredPlayerName(BetterForgeChatUtilities.java:23) ~[BetterForgeChat-MC1182-V1.1.0.jar%2348!/:1.1] {re:classloading}
        at com.jeremiahbl.bfcmod.utils.BetterForgeChatUtilities.getFormattedPlayerName(BetterForgeChatUtilities.java:29) ~[BetterForgeChat-MC1182-V1.1.0.jar%2348!/:1.1] {re:classloading}
        at com.jeremiahbl.bfcmod.events.PlayerEventHandler.onTabListNameFormatEvent(PlayerEventHandler.java:31) ~[BetterForgeChat-MC1182-V1.1.0.jar%2348!/:1.1] {re:classloading}
        at net.minecraftforge.eventbus.ASMEventHandler_879_PlayerEventHandler_onTabListNameFormatEvent_TabListNameFormat.invoke(.dynamic) ~[?:?] {}
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!/:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?] {}
        at net.minecraftforge.event.ForgeEventFactory.getPlayerTabListDisplayName(ForgeEventFactory.java:256) ~[forge-1.18.2-40.1.61-universal.jar%23166!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
        at net.minecraft.server.level.ServerPlayer.m_8957_(ServerPlayer.java:1355) ~[server-1.18.2-20220404.173914-srg.jar%23161!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:botania_xplat.mixins.json:MixinServerPlayer,pl:mixin:APP:flan.mixins.json:PlayerClaimMixin,pl:mixin:APP:assets/the_vault/the_vault.mixins.json:MixinServerPlayerEntity,pl:mixin:A}
        at net.minecraft.network.protocol.game.ClientboundPlayerInfoPacket.<init>(ClientboundPlayerInfoPacket.java:28) ~[server-1.18.2-20220404.173914-srg.jar%23161!/:?] {re:classloading}
        at net.minecraft.server.level.ServerPlayerGameMode.m_9273_(ServerPlayerGameMode.java:64) ~[server-1.18.2-20220404.173914-srg.jar%23161!/:?] {re:computing_frames,re:classloading}
        at net.minecraft.server.level.ServerPlayer.m_143427_(ServerPlayer.java:1537) ~[server-1.18.2-20220404.173914-srg.jar%23161!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:botania_xplat.mixins.json:MixinServerPlayer,pl:mixin:APP:flan.mixins.json:PlayerClaimMixin,pl:mixin:APP:assets/the_vault/the_vault.mixins.json:MixinServerPlayerEntity,pl:mixin:A}
        at net.minecraft.server.players.PlayerList.m_11261_(PlayerList.java:155) ~[server-1.18.2-20220404.173914-srg.jar%23161!/:?] {re:mixin,xf:fml:xaeroworldmap:xaero_wm_playerlist_sendworldinfo,xf:fml:xaerominimap:xaero_playerlist_sendworldinfo,re:classloading,xf:fml:xaeroworldmap:xaero_wm_playerlist_sendworldinfo,xf:fml:xaerominimap:xaero_playerlist_sendworldinfo,pl:mixin:A}
        at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_143699_(ServerLoginPacketListenerImpl.java:138) ~[server-1.18.2-20220404.173914-srg.jar%23161!/:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_10055_(ServerLoginPacketListenerImpl.java:125) ~[server-1.18.2-20220404.173914-srg.jar%23161!/:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_10050_(ServerLoginPacketListenerImpl.java:69) ~[server-1.18.2-20220404.173914-srg.jar%23161!/:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.network.Connection.m_129483_(Connection.java:241) ~[server-1.18.2-20220404.173914-srg.jar%23161!/:?] {re:classloading}
        at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:142) ~[server-1.18.2-20220404.173914-srg.jar%23161!/:?] {re:classloading}
        at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:916) ~[server-1.18.2-20220404.173914-srg.jar%23161!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:flan.mixins.json:MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:APP:terrablender.mixins.json:MixinMinecraftServer,pl:mixin:APP:assets/the_vault/the_vault.mixins.json:AccessorMinecraftServer,pl:mixin:APP:assets/the_vault/the_vault.mixins.json:MixinMinecraftServer,pl:mixin:A}
        at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:326) ~[server-1.18.2-20220404.173914-srg.jar%23161!/:?] {re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:842) ~[server-1.18.2-20220404.173914-srg.jar%23161!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:flan.mixins.json:MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:APP:terrablender.mixins.json:MixinMinecraftServer,pl:mixin:APP:assets/the_vault/the_vault.mixins.json:AccessorMinecraftServer,pl:mixin:APP:assets/the_vault/the_vault.mixins.json:MixinMinecraftServer,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:685) ~[server-1.18.2-20220404.173914-srg.jar%23161!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:flan.mixins.json:MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:APP:terrablender.mixins.json:MixinMinecraftServer,pl:mixin:APP:assets/the_vault/the_vault.mixins.json:AccessorMinecraftServer,pl:mixin:APP:assets/the_vault/the_vault.mixins.json:MixinMinecraftServer,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[server-1.18.2-20220404.173914-srg.jar%23161!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:flan.mixins.json:MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:APP:terrablender.mixins.json:MixinMinecraftServer,pl:mixin:APP:assets/the_vault/the_vault.mixins.json:AccessorMinecraftServer,pl:mixin:APP:assets/the_vault/the_vault.mixins.json:MixinMinecraftServer,pl:mixin:A}
        at java.lang.Thread.run(Thread.java:833) [?:?] {}

[17:28:04] [Server thread/ERROR] [ne.mi.ev.EventBus/EVENTBUS]: Exception caught during firing event: null
        Index: 1
        Listeners:
                0: NORMAL
                1: ASM: com.jeremiahbl.bfcmod.events.PlayerEventHandler@644e2886 onTabListNameFormatEvent(Lnet/minecraftforge/event/entity/player/PlayerEvent$TabListNameFormat;)V
java.lang.NullPointerException
[17:28:04] [Server thread/ERROR] [minecraft/ServerLoginPacketListenerImpl]: Couldn't place player in world
java.lang.NullPointerException: null

**Comment by abc123me** [comment]
Can you send the config file for the mod?
It should be in config/

**Comment by ThirtyTwelveNor** [comment]
there was no config generated :D

**Comment by abc123me** [comment]
That's not good! Give me 15mins or so to look into it, what version are you using?

**Comment by ThirtyTwelveNor** [comment]
latest/MC1182-V1.1.0.jar
and forge 1.18.2-40.1.61
Thanks!

**Comment by abc123me** [comment]
Good, I found the problem but do not understand how the issue occurred, it looks like the server started and didn't generate a configuration file for the mod. This (should be) impossible unless the player joins before the server's world is loaded. Can you send me complete server log files and double check that there is no `config/bfcmod-common.toml` file in your server's working directory?

**Comment by ThirtyTwelveNor** [comment]
ow i did not know it was named bfc my bad.
here is config(i did not edit this tho)

[BetterForgeChatModConfig]
	#  Controls the chat message format
	#    $prefix is replaced by the user's prefix or nothing if the user has no prefix
	#    $suffix is replaced by the user's suffix or nothing if the user has no suffix
	#    $name is replaced by the user's name, or nickname if they have one
	playerNameFormat = "$prefix$name$suffix"
	#  Controls the chat message format
	#    $time is replaced by the timestamp field or nothing if disabled
	#    $name is replaced by the user's name, or nickname if they have one
	#    $msg is replaced by the username's message (if you use it more then once it WILL break this mod)
	chatMessageFormat = "$time | $name: $msg"
	#  Timestamp format following the java SimpleDateFormat
	#    Read more here: https://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html
	timestampFormat = "HH:mm"
	#  Enables or disables the filling in of timestamps
	enableTimestamp = true
	#  Enables or disables FTB essentials nickname integration
	useFtbEssentials = true
	#  Enables or disables LuckPerms integration
	useLuckPerms = true
	#  Enables or disables markdown styling
	markdownEnabled = true
	#  Enables or disables custom tab list information
	tabList = true
	#  Enables or disables prefixes&suffixes in the tab list
	tabListMetadata = true
	#  Enables or disables nicknames in the tab list
	tabListNicknames = false
	#  Enables or disables the /colors command
	enableColorsCommand = true

**Comment by ThirtyTwelveNor** [comment]
[2022-12-07-1.log](https://github.com/abc123me/BetterForgeChat/files/10178139/2022-12-07-1.log)

**Comment by abc123me** [comment]
Are you using FTBEssentials in the pack?

**Comment by ThirtyTwelveNor** [comment]
I am, and luckperms

**Comment by ThirtyTwelveNor** [comment]
https://www.curseforge.com/minecraft/modpacks/vault-hunters-1-18-2/files/4119443
+
https://www.curseforge.com/minecraft/mc-mods/luckperms/files/3828099
https://www.curseforge.com/minecraft/mc-mods/ftb-essentials-forge/files/3773058
https://www.curseforge.com/minecraft/mc-mods/mc2discord/files/4119890
https://www.curseforge.com/minecraft/mc-mods/crash-utilities/files/3808085

**Comment by abc123me** [comment]
OK, I think I have the issue fixed, I will prepare you a release. Looks like FTBessentials is providing a null nickname for your player, and that was tripping up a substitution I had in the configuration file. My version of FTBessentials doesn't do this. But nevertheless the mod should work with any version of FTBessentials.

This will be released as version 1.1.1, and I will provide a link once gradle finishes building the mod! Sorry for the inconvenience!

**Comment by abc123me** [comment]
https://github.com/abc123me/BetterForgeChat/releases/tag/V1.1.1

**Comment by abc123me** [comment]
That should fix it! Please close the issue if it does, if it doesn't let me know! I'm currently adding discord integration right now and don't want this bug propagating into any future versions.

**Comment by ThirtyTwelveNor** [comment]
Works!

**Comment by abc123me** [comment]
CurseForge version updated!
